server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      database: spitdb
      host: 192.168.229.134
  redis:
    host: 192.168.229.134
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true